from typing import Any

from sqlalchemy import Computed, ForeignKey, Text
from sqlalchemy.dialects.postgresql import TSVECTOR
from sqlalchemy.orm import Mapped, mapped_column, relationship
from pgvector.sqlalchemy import Vector

from app.db.base_class import Base


class Chunk(Base):
    """A text chunk extracted from a document during processing.

    Each chunk preserves provenance — the ability to trace the text
    back to the exact source page(s) and character offsets in the
    original document.

    Lifecycle:
        - Created during document processing (Milestone 3).
        - Deleted when the parent document is deleted (CASCADE).
    """

    __tablename__ = "chunks"

    document_id: Mapped[int] = mapped_column(
        ForeignKey("documents.id", ondelete="CASCADE"), nullable=False, index=True
    )

    chunk_index: Mapped[int] = mapped_column(nullable=False)
    """Position of this chunk within the document (0-based, sequential)."""

    content: Mapped[str] = mapped_column(Text, nullable=False)
    """The actual text content of this chunk."""

    page_start: Mapped[int] = mapped_column(nullable=False)
    """First page this chunk contains text from (1-based)."""

    page_end: Mapped[int] = mapped_column(nullable=False)
    """Last page this chunk contains text from (1-based)."""

    char_offset_start: Mapped[int] = mapped_column(nullable=False)
    """Start character offset in the full concatenated document text."""

    char_offset_end: Mapped[int] = mapped_column(nullable=False)
    """End character offset in the full concatenated document text."""

    chunk_size: Mapped[int] = mapped_column(nullable=False)
    """Length of the content field in characters."""

    embedding: Mapped[Any] = mapped_column(
        Vector(384), nullable=True
    )
    """384-dimensional embedding vector for semantic search.

    Generated by EmbeddingService using sentence-transformers/all-MiniLM-L6-v2.
    NULL for chunks that have not yet been embedded.
    Populated via POST .../embed endpoint (Milestone 5).
    """

    search_vector: Mapped[Any] = mapped_column(
        TSVECTOR,
        Computed("to_tsvector('english', content)", persisted=True),
        nullable=True,
    )
    """PostgreSQL tsvector for full-text search (auto-maintained generated column).

    GENERATED ALWAYS AS (to_tsvector('english', content)) STORED.
    PostgreSQL updates this automatically on every INSERT or UPDATE to `content`.
    Never set or updated by application code.
    """
